In [1]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm

pd.set_option('display.expand_frame_repr', False)
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
pd.options.display.float_format = '{:,.2f}'.format

In [2]:
# reading dataset for China IPUMS
data_china = pd.read_csv('/users/quasar/downloads/ipumsi_00013.csv')
data_china.head()

   COUNTRY  YEAR    SAMPLE  SERIAL  HHWT  PERNUM  PERWT  RESIDENT  EDATTAIN  EDATTAIND  INDGEN
0       76  1960  76196001    1000  5.00       1   5.00      1.00         1        110      10
1       76  1960  76196001    1000  5.00       2   5.00      1.00         1        110       0
2       76  1960  76196001    1000  5.00       3   5.00      1.00         1        120       0
3       76  1960  76196001    1000  5.00       4   5.00      1.00         1        120       0
4       76  1960  76196001    1000  5.00       5   5.00      1.00         1        120       0

In [3]:
data_china.head()

   COUNTRY  YEAR    SAMPLE  SERIAL  HHWT  PERNUM  PERWT  RESIDENT  EDATTAIN  EDATTAIND  INDGEN
0       76  1960  76196001    1000  5.00       1   5.00      1.00         1        110      10
1       76  1960  76196001    1000  5.00       2   5.00      1.00         1        110       0
2       76  1960  76196001    1000  5.00       3   5.00      1.00         1        120       0
3       76  1960  76196001    1000  5.00       4   5.00      1.00         1        120       0
4       76  1960  76196001    1000  5.00       5   5.00      1.00         1        120       0

In [4]:
# Calculating sample size 
data_china.groupby('YEAR')['INDGEN'].value_counts()

YEAR  INDGEN
1960  0         10088132
      10         2674574
      30          434256
      60          389448
      114         260857
      80          223944
      120         204426
      50          174350
      100         141387
      112          81994
      999          81314
      70           48931
      111          42413
      113          42238
      90           35759
      40           30660
      20           29086
1970  0         16850161
      10         3590690
      30          848757
      60          784620
      120         622933
      50          461937
      80          331367
      100         330424
      112         242626
      999         188844
      114         129353
      113          97027
      90           96223
      40           76757
      111          68412
      20           48386
      70           21199
1980  0         18877903
      10         3142775
      30         1711450
      60         1135651
      50          782928
      120         625234
      80          484265
      114         470817
      100         458497
      112         425454
      111         385799
      70          223003
      113         214893
      90          207870
      999          88967
      40           80597
      20           62650
1991  0         10707861
      10         1744955
      30          876308
      60          721785
      114         425482
      120         410665
      50          404157
      112         328851
      100         295936
      80          276801
      111         269268
      70          194425
      113         154214
      90          108559
      20           56750
      40           37124
      999          32571
2000  0         12491513
      10         1834787
      60         1029907
      30          978976
      120         578764
      50          517060
      114         440335
      112         439850
      100         409948
      80          355439
      111         351683
      70          338514
      113         262280
      999          94109
      90           85196
      40           36283
      20           29768
2010  0         11484365
      10         2015634
      60         1396308
      30         1059708
      50          647508
      120         607521
      100         507914
      112         500420
      999         492315
      111         442735
      80          421285
      113         318339
      70          278023
      114         252910
      90           86715
      40           77952
      20           45508
      130            261
      998             51
Name: INDGEN, dtype: int64

In [5]:
data_china.groupby('YEAR')['EDATTAIN'].value_counts(normalize=True)

YEAR  EDATTAIN
1960  1          0.80
      0          0.16
      2          0.03
      3          0.01
      9          0.00
      4          0.00
1970  1          0.77
      0          0.15
      2          0.05
      3          0.02
      4          0.01
      9          0.00
1980  1          0.67
      0          0.14
      2          0.12
      3          0.05
      4          0.01
      9          0.00
1991  1          0.65
      2          0.14
      0          0.12
      3          0.07
      4          0.02
2000  1          0.54
      2          0.20
      0          0.12
      3          0.11
      4          0.03
2010  1          0.52
      2          0.25
      3          0.17
      4          0.05
Name: EDATTAIN, dtype: float64

In [6]:
data_china.groupby(['YEAR','INDGEN'])['EDATTAIN'].value_counts(normalize=True)

YEAR  INDGEN  EDATTAIN
1960  0       1          0.73
              0          0.23
              2          0.02
              3          0.00
              9          0.00
              4          0.00
      10      1          0.99
              2          0.00
              9          0.00
              3          0.00
              4          0.00
      20      1          0.96
              2          0.02
              3          0.01
              4          0.01
              9          0.00
      30      1          0.90
              2          0.06
              3          0.02
              9          0.01
              4          0.01
      40      1          0.89
              2          0.07
              3          0.02
              4          0.01
              9          0.01
      50      1          0.95
              2          0.02
              9          0.01
              4          0.01
              3          0.01
      60      1          0.85
              2          0.10
              3          0.03
              9          0.01
              4          0.01
      70      1          0.93
              2          0.05
              3          0.01
              9          0.01
              4          0.00
      80      1          0.91
              2          0.06
              3          0.02
              9          0.01
              4          0.00
      90      1          0.37
              2          0.35
              3          0.24
              4          0.03
              9          0.00
      100     1          0.65
              2          0.20
              3          0.10
              4          0.05
              9          0.01
      111     1          0.37
              3          0.22
              2          0.22
              4          0.18
              9          0.00
      112     3          0.39
              1          0.31
              2          0.24
              4          0.06
              9          0.00
      113     1          0.56
              4          0.23
              2          0.12
              3          0.09
              9          0.01
      114     1          0.93
              2          0.04
              4          0.01
              3          0.01
              9          0.01
      120     1          0.98
              9          0.01
              2          0.01
              3          0.00
              4          0.00
      999     1          0.80
              9          0.10
              2          0.06
              3          0.03
              4          0.01
1970  0       1          0.72
              0          0.22
              2          0.05
              3          0.01
              4          0.00
              9          0.00
      10      1          0.99
              2          0.01
              3          0.00
              4          0.00
              9          0.00
      20      1          0.93
              2          0.04
              3          0.02
              4          0.01
              9          0.00
      30      1          0.82
              2          0.12
              3          0.05
              4          0.02
              9          0.00
      40      1          0.79
              2          0.12
              3          0.06
              4          0.03
              9          0.00
      50      1          0.94
              2          0.04
              4          0.01
              3          0.01
              9          0.00
      60      1          0.78
              2          0.16
              3          0.05
              4          0.01
              9          0.00
      70      1          0.87
              2          0.09
              3          0.03
              4          0.00
              9          0.00
      80      1          0.84
              2          0.12
              3          0.03
              4          0.01
              9          0.00
      90      2          0.36
              3          0.33
              1          0.23
              4          0.06
              9          0.01
      100     1          0.54
              2          0.25
              3          0.13
              4          0.07
              9          0.01
      111     2          0.32
              1          0.26
              3          0.25
              4          0.16
              9          0.01
      112     3          0.49
              1          0.27
              2          0.14
              4          0.10
              9          0.00
      113     1          0.52
              4          0.20
              2          0.19
              3          0.08
              9          0.01
      114     1          0.73
              2          0.16
              3          0.06
              4          0.04
              9          0.01
      120     1          0.97
              2          0.03
              3          0.00
              9          0.00
              4          0.00
      999     1          0.84
              2          0.11
              3          0.04
              4          0.01
              9          0.00
1980  0       1          0.65
              0          0.22
              2          0.10
              3          0.02
              4          0.00
              9          0.00
      10      1          0.96
              2          0.03
              3          0.01
              4          0.00
              9          0.00
      20      1          0.78
              2          0.12
              3          0.07
              4          0.03
              9          0.00
      30      1          0.64
              2          0.24
              3          0.09
              4          0.03
              9          0.00
      40      1          0.46
              2          0.23
              3          0.21
              4          0.10
              9          0.00
      50      1          0.84
              2          0.11
              3          0.03
              4          0.02
              9          0.00
      60      1          0.56
              2          0.31
              3          0.11
              4          0.02
              9          0.00
      70      1          0.73
              2          0.21
              3          0.05
              4          0.01
              9          0.00
      80      1          0.65
              2          0.22
              3          0.10
              4          0.02
              9          0.00
      90      3          0.47
              2          0.30
              4          0.12
              1          0.11
              9          0.00
      100     1          0.38
              2          0.26
              3          0.23
              4          0.12
              9          0.00
      111     1          0.41
              2          0.26
              3          0.21
              4          0.11
              9          0.00
      112     3          0.44
              1          0.22
              4          0.20
              2          0.14
              9          0.00
      113     1          0.34
              2          0.29
              4          0.20
              3          0.17
              9          0.00
      114     1          0.70
              2          0.20
              3          0.08
              4          0.03
              9          0.00
      120     1          0.87
              2          0.12
              3          0.00
              9          0.00
              4          0.00
      999     1          0.78
              2          0.13
              3          0.06
              4          0.03
              9          0.00
1991  0       1          0.67
              0          0.18
              2          0.10
              3          0.03
              4          0.01
      10      1          0.92
              2          0.06
              3          0.02
              4          0.00
      20      1          0.71
              2          0.16
              3          0.10
              4          0.04
      30      1          0.53
              2          0.29
              3          0.14
              4          0.04
      40      1          0.34
              3          0.29
              2          0.23
              4          0.14
      50      1          0.76
              2          0.16
              3          0.05
              4          0.02
      60      1          0.43
              2          0.32
              3          0.21
              4          0.04
      70      1          0.58
              2          0.28
              3          0.12
              4          0.02
      80      1          0.54
              2          0.27
              3          0.15
              4          0.04
      90      3          0.51
              4          0.20
              2          0.19
              1          0.09
      100     1          0.32
              3          0.30
              2          0.23
              4          0.15
      111     1          0.38
              2          0.25
              3          0.24
              4          0.14
      112     3          0.43
              4          0.23
              1          0.21
              2          0.13
      113     2          0.27
              3          0.26
              1          0.24
              4          0.24
      114     1          0.56
              2          0.28
              3          0.13
              4          0.04
      120     1          0.81
              2          0.17
              3          0.02
              4          0.00
      999     1          0.61
              2          0.22
              3          0.13
              4          0.04
2000  0       1          0.57
              0          0.19
              2          0.17
              3          0.06
              4          0.01
      10      1          0.84
              2          0.12
              3          0.03
              4          0.00
      20      1          0.61
              2          0.20
              3          0.15
              4          0.04
      30      1          0.42
              2          0.33
              3          0.21
              4          0.04
      40      3          0.35
              1          0.27
              2          0.26
              4          0.12
      50      1          0.64
              2          0.25
              3          0.09
              4          0.02
      60      2          0.32
              1          0.32
              3          0.31
              4          0.05
      70      1          0.45
              2          0.33
              3          0.20
              4          0.02
      80      1          0.42
              2          0.32
              3          0.23
              4          0.04
      90      3          0.53
              4          0.26
              2          0.14
              1          0.06
      100     3          0.37
              1          0.26
              2          0.23
              4          0.14
      111     3          0.35
              2          0.24
              1          0.22
              4          0.20
      112     3          0.47
              4          0.25
              2          0.14
              1          0.14
      113     3          0.33
              2          0.23
              4          0.23
              1          0.21
      114     1          0.38
              2          0.34
              3          0.23
              4          0.05
      120     1          0.65
              2          0.29
              3          0.06
              4          0.00
      999     1          0.45
              2          0.27
              3          0.23
              4          0.06
2010  0       1          0.67
              2          0.22
              3          0.09
              4          0.02
      10      1          0.65
              2          0.25
              3          0.08
              4          0.01
      20      3          0.33
              1          0.30
              2          0.26
              4          0.11
      30      2          0.35
              3          0.34
              1          0.25
              4          0.06
      40      1          0.36
              3          0.28
              2          0.27
              4          0.08
      50      1          0.45
              2          0.37
              3          0.16
              4          0.02
      60      3          0.40
              2          0.33
              1          0.21
              4          0.06
      70      2          0.38
              3          0.29
              1          0.29
              4          0.04
      80      3          0.35
              2          0.32
              1          0.24
              4          0.09
      90      3          0.42
              4          0.41
              2          0.12
              1          0.05
      100     3          0.42
              4          0.25
              2          0.18
              1          0.15
      111     3          0.39
              4          0.23
              2          0.22
              1          0.15
      112     4          0.49
              3          0.32
              2          0.11
              1          0.08
      113     3          0.45
              4          0.30
              2          0.16
              1          0.09
      114     3          0.38
              2          0.34
              1          0.19
              4          0.10
      120     1          0.46
              2          0.38
              3          0.16
              4          0.00
      130     4          0.42
              3          0.29
              2          0.17
              1          0.12
      998     3          0.43
              2          0.24
              4          0.20
              1          0.14
      999     3          0.30
              2          0.30
              1          0.30
              4          0.10
Name: EDATTAIN, dtype: float64

In [7]:
data = data_china.copy()
data.head()

   COUNTRY  YEAR    SAMPLE  SERIAL  HHWT  PERNUM  PERWT  RESIDENT  EDATTAIN  EDATTAIND  INDGEN
0       76  1960  76196001    1000  5.00       1   5.00      1.00         1        110      10
1       76  1960  76196001    1000  5.00       2   5.00      1.00         1        110       0
2       76  1960  76196001    1000  5.00       3   5.00      1.00         1        120       0
3       76  1960  76196001    1000  5.00       4   5.00      1.00         1        120       0
4       76  1960  76196001    1000  5.00       5   5.00      1.00         1        120       0

In [8]:
data['EDATTAIN'].unique()

array([1, 0, 2, 3, 4, 9])

In [9]:
data['EDATTAIND'].unique()

array([110, 120,   0, 130, 212, 311, 400, 221, 312, 999])

In [10]:
data['EDATTAIN'].replace(to_replace= 0, value='NIU (not in universe)', inplace=True)
data['EDATTAIN'].replace(to_replace= 1, value='Less than primary completed', inplace=True)
data['EDATTAIN'].replace(to_replace= 2, value='Primary completed', inplace=True)
data['EDATTAIN'].replace(to_replace= 3, value='Secondary completed', inplace=True)
data['EDATTAIN'].replace(to_replace= 4, value='University completed', inplace=True)
data['EDATTAIN'].replace(to_replace= 9, value='Unkwown', inplace=True)

In [ ]:
data['INDGEN'].replace(to_replace= 0, value='Not In Universe', inplace=True)
data['INDGEN'].replace(to_replace= 10, value='Agriculture', inplace=True)
data['INDGEN'].replace(to_replace= 20, value='Industry', inplace=True)
data['INDGEN'].replace(to_replace= 30, value='Industry', inplace=True)
data['INDGEN'].replace(to_replace= 40, value='Skilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 50, value='Industry', inplace=True)
data['INDGEN'].replace(to_replace= 60, value='Unskilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 70, value='Unskilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 80, value='Unskilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 90, value='Skilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 100, value='Skilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 111, value='Skilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 112, value='Skilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 113, value='Skilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 114, value='Skilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 120, value='Unskilled Service', inplace=True)
data['INDGEN'].replace(to_replace= 130, value='Industry', inplace=True)
data['INDGEN'].replace(to_replace= 998, value='Response Suppressed', inplace=True)
data['INDGEN'].replace(to_replace= 999, value='Unknown', inplace=True)

In [ ]:
result = data.groupby(['YEAR','INDGEN'])['EDATTAIN'].value_counts(normalize=True)

In [ ]:
result.to_excel("/users/quasar/downloads/Brazil.xlsx")